### ISSUE TITLE
Add MacOS Support

### ISSUE THREAD

**Issue by jordanstreiff** [naclander/Calibre-Remarkable-Device-Driver-Plugin#3]
Feature request to add MacOS support. What is preventing this?

**Comment by r0bbie** [comment]
Am also very hopeful for macOS support 🙏

**Comment by naclander** [comment]
I don't see a reason why macOS shouldn't be supported. Support just involved adding the `osx` string. `main` should now be updated to reflect this, and you can find the latest release with macOS support [here](https://github.com/naclander/Calibre-Remarkable-Device-Driver-Plugin/releases/tag/1.2.0)

As I don't have a computer running macOS I can't officially verify this, but I have more confidence than the Windows version, since macOS should be more closely similar to Linux. 

If you have any issues running this plugin on macOS please don't hesitate to open a new issue.
